### PR TITLE
Unwrap all IOExceptions from MappingIterator

### LINKED ISSUE #71: IOExceptions during reading of events are wrapped in RuntimeExceptions
Happens for example with an `SSLHandshakeException`. The `MappingIterator` wraps it into `RuntimeException` but we only unwrap a very specific `RuntimeJsonMappingException`.

    java.lang.RuntimeException: SSL peer shut down incorrectly  
    at com.fasterxml.jackson.databind.MappingIterator.next(MappingIterator.java:196)  
    at org.zalando.fahrschein.NakadiReader.readEvent(NakadiReader.java:205)

### PR DESCRIPTION
**Pull request by jhorstmann**
This fixes #71

### CODE REVIEW

File: src/main/java/org/zalando/fahrschein/NakadiReader.java [hunk 1]
```diff
@@ -200,13 +199,15 @@ private Cursor readCursor(JsonParser jsonParser) throws IOException {
         return events;
     }
 
-    private void readEvent(final Iterator<T> source, final List<T> target) throws JsonMappingException {
+    private void readEvent(final Iterator<T> source, final List<T> target) throws IOException {
         try {
             target.add(source.next());
```
Comment (jhorstmann) [inline src/main/java/org/zalando/fahrschein/NakadiReader.java]: I'm wondering if the `hasNext` method is also allowed to throw runtime exceptions.

File: src/main/java/org/zalando/fahrschein/NakadiReader.java [hunk 2]
```diff
@@ -194,23 +193,26 @@ private Cursor readCursor(JsonParser jsonParser) throws IOException {
...
-            target.add(source.next());
-        } catch (final RuntimeJsonMappingException e) {
-            final Throwable cause = e.getCause();
-            if (cause instanceof JsonMappingException) {
-                listener.onMappingException((JsonMappingException) cause);
-            } else {
-                throw e;
+        while (true) {
+            try {
+                // MappingIterator#hasNext can theoretically also throw RuntimeExceptions, that's why we use this strange loop structure
```
Comment (lukasniemeier-zalando) [inline src/main/java/org/zalando/fahrschein/NakadiReader.java]: But why?

Comment (jhorstmann) [inline src/main/java/org/zalando/fahrschein/NakadiReader.java]: See https://github.com/FasterXML/jackson-databind/blob/jackson-databind-2.7.6/src/main/java/com/fasterxml/jackson/databind/MappingIterator.java#L180 and https://github.com/FasterXML/jackson-databind/blob/jackson-databind-2.7.6/src/main/java/com/fasterxml/jackson/databind/MappingIterator.java#L409

Not sure in what cases it can really happen, but according to the code it's possible.

Comment (lukasniemeier-zalando) [inline src/main/java/org/zalando/fahrschein/NakadiReader.java]: But can we even recover from such cases (i.e. Jackson unable to proceed to next element in events array)?

Comment (tmuehl) [inline src/main/java/org/zalando/fahrschein/NakadiReader.java]: @lukasniemeier-zalando This can happen if the connection breaks (or is just dropped by Nakadi). In this case we can easily recover by reconnecting. In the catch block he explicitly looks for an IOException, so I think it's fine.

We encounter this exact case in our Team an currently recover by catching this IOException and reconnect.

**Comment by tmuehl** [comment]
👍

File: src/main/java/org/zalando/fahrschein/NakadiReader.java (hunk 2 above)
Comment (lukasniemeier-zalando) [inline src/main/java/org/zalando/fahrschein/NakadiReader.java]: Ah now I see `IOException`s are propagated, only `JsonMappingException` are notified.

**Comment by lukasniemeier-zalando** [comment]
:+1:
